package:
  name: bammap2
  version: 0.1.4

source:
  path: .


build:
  number: 0
  script: cargo install --path . --root $PREFIX --locked


requirements:
  build:
    - rust
    - compilers
    - clang
    - pkg-config
    - clangdev
    - automake
    - autoconf
    - jemalloc
    - make 
  host:
    - openssl
    - zlib
  run:
    - openssl
    - zlib


about:
  summary: A lightweight wrapper to run minimap2 (v2.30) alignments directly on BAM file
  license: BSD-3-Clause